name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: get current pom version of project
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project

    - name: login to docker registry
      uses: docker/login-action@v3
      with:
        username: emersongama5
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build and push docker image to registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: emersongama5/tarefa-api:latest, emersongama5/tarefa-api:${{ steps.project.outputs.version }}